---
- name: Capture pre-maintenance VXLAN output from Nexus switch(es)
  hosts: "{{ target_host }}" ## User will be prompted for this information below
  gather_facts: false
  connection: local
  vars_prompt:
    ## Prompt user for host(s) or IP address(es) to be configured
  - name: target_host
    prompt: "Enter Nexus Switch Name or IP"
    private: no

    ## Prompt user for host(s) or IP address(es) to be configured
  - name: filename_prepend
    prompt: "Enter Snapshot Capture Type; pre or post"
    private: no

    ## Take user input for target_host above and add to the hosts parameter
  tasks:
    - add_host:
        name: "{{ target_host }}"
  hosts: "{{ target_host }}"


  tasks:
    - name: Query Switch(es) operational status BEFORE changes
      nxos_command:
        commands:
          - show hostname
          - show ip ospf neighbors
          - show bgp l2vpn evpn summary
          - show lldp neighbor
          - show interface status
          - show nve peers
          #- show bgp private attribute
          - show vxlan
          - show nve internal vni all 
          - show mac address-table
          - show interface ethernet1/1-48 switchport
          - show interface trunk
          - show interface loopback0
          - show interface loopback5
          - show interface nve1
          #- show system resources  all-modules 
          - show module
          - show environment power
          - show run
          - show hostname
          - show clock
      
      register: print_output
    - debug: var=print_output.stdout_lines
    
    ## Capture the output from the previous show commands into a file for later forensics, in case there is an issue.
    - name: Capture query output from Switch(es) and write to text file.
      copy: 
        content: "{{ print_output.stdout_lines | to_nice_yaml(indent=2) }}" 
        dest: "/mnt/c/Users/criley/Documents/ansible_output_captures/{{ inventory_hostname }}_vxlan_{{ filename_prepend }}_maint.txt"