---
- name: Reprovision VPC Port-channel Trunk Interfaces on Nexus Switch
  hosts: "{{ target_host }}" ## User will be prompted for this information below
  gather_facts: false
  connection: local
  vars_prompt:
    ## Prompt user for host(s) or IP address(es) to be configured
  - name: target_host
    prompt: "Enter Nexus Switch(es) Name?"
    private: no

    ## Prompt user for Trunk Interfaces to Reprovision
  - name: vpc_trunk # User input variable
    private: no
    prompt: "Enter VPC Trunk Port-channel(s) to Reprovision?"

    ## Prompt user for VLAN Number(s) to Add to Trunk(s)
  - name: trunk_vlans #User input variable
    private: no
    prompt: "Enter VLAN(s) to Span VPC Trunk Port-channel(s)?"

    ## Prompt user for Trunk Interface(s) Description
  - name: trunk_desc #User input variable
    private: no
    prompt: "Enter Description for VPC Trunk Port-channel(s)?"

    ## Take user input for target_host above and add to the hosts parameter
  tasks:
    - add_host:
        name: "{{ target_host }}"
  hosts: "{{ target_host }}"

############### START OF SCRIPT EXECUTION SEQUENCE #############
  tasks:

    - name: Display Switch(es) VPC Trunk(s) Status and Configuration BEFORE changes
      nxos_command:
        commands:
          - show hostname 
          - show run interface {{ vpc_trunk }}
          - show interface {{ vpc_trunk }} status
          - show hostname
          - show clock
      register: print_output
    - debug: var=print_output.stdout_lines

    ## Pause script to allow user to read/review candidate configuration file before sending to device(s) ; User must press key to Continue or Abort
    - pause:
       prompt: "!!! REVIEW ABOVE CURENT CONFIGURATION !!! To CONTINUE script Press (Enter) or To CANCEL script Press (Ctrl + C then A) "

    ## Capture the output from the previous show commands into a file for later forensics, in case there is an issue.
    - name: Copy Switch(es) Interface(s) configuration to External File, BEFORE Changes
      copy: 
        content: "{{ print_output.stdout_lines | to_nice_yaml(indent=2) }}" 
        dest: "/mnt/c/Users/criley/Documents/ansible_output_captures/{{ inventory_hostname }}_interface_backup_config.txt"

    ## Remove Description and Prune VPC Trunk
    - name: Remove Description and Prune VLAN(s) from VPC Trunk(s)
      cisco.nxos.nxos_command:
        commands:
        - configure terminal
        - command: interface {{ vpc_trunk }}
        - command: no description
        - command: switchport trunk allowed vlan none
        - command: end

    ## Add Description and Span VLAN(s) to VPC Trunk(s)
    - name: Add VLAN(s) to Target Trunk Interface(s) and Activate
      cisco.nxos.nxos_command:
        commands:
        - configure terminal
        - command: interface {{ vpc_trunk }}
        - command: description {{ trunk_desc }}
        - command: switchport trunk allowed vlan add {{ trunk_vlans }}
        - command: no shutdown
        - command: end

    - pause:
        prompt: "Allow Switch(es) 10 Seconds to Synchronize VLAN Configuration"
        seconds: 10

    - name: Save switch(es) configuration after script tasks complete
      nxos_config:
        save_when: always

    ## Display Interfaces current configuration and save to file
    - name: Display Switch(es) Desired Trunk Interface(s) status AFTER changes
      nxos_command:
        commands:
          - show hostname 
          - show run interface {{ vpc_trunk }}
          - show interface {{ vpc_trunk }} status
          - show start interface {{ vpc_trunk }}
          - show port-channel database interface {{ vpc_trunk }}
          - show hostname
          - show clock
      register: print_output
    - debug: var=print_output.stdout_lines